name: nerdster
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+137

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.6
  crypto: ^3.0.3
  google_fonts: ^6.2.1
  intl: ^0.20.1
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  json_diff: ^0.2.1
  qr_flutter: ^4.1.0
  cryptography: ^2.7.0
  jwk: ^0.2.3
  convert: ^3.1.1
  collection: ^1.18.0
  fake_cloud_firestore: ^4.0.0
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  flutter_linkify: ^6.0.0
  package_info_plus: ^8.1.1
  cloud_functions: ^6.0.0
  graphview: ^1.5.1
  web: ^1.1.1
  float_column: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
